# Generated by Django 3.2.5 on 2021-07-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('ingredients', models.TextField(null=True)),
                ('method', models.TextField(null=True)),
                ('prepare_time', models.CharField(max_length=200)),
                ('cook_time', models.CharField(max_length=200)),
                ('uploader', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
