# Generated by Django 3.2.5 on 2021-07-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
