# Generated by Django 3.2.6 on 2022-05-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_pagecontents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('page_name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
