# Generated by Django 3.2.6 on 2022-05-05 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
